const PrePage = () => {
  return (
    <div className="">
      <div>header box</div>
      <div className="px-[150px]">
        cards
        <p>hello 1</p>
        <p>hello 2</p>
        <p>hello 3</p>
        <p>hello 4</p>
        <p>hello 5</p>
        <p>hello 6</p>
        <p>hello 7</p>
        <p>hello 8</p>
        <p>hello 9</p>
        <p>hello 10</p>
        <p>hello 11</p>
        <p>hello 12</p>
        <p>hello 13</p>
        <p>hello 14</p>
        <p>hello 15</p>
        <p>hello 16</p>
        <p>hello 17</p>
        <p>hello 18</p>
        <p>hello 19</p>
        <p>hello 20</p>
        <p>hello 21</p>
        <p>hello 22</p>
        <p>hello 23</p>
        <p>hello 24</p>
        <p>hello 25</p>
        <p>hello 26</p>
        <p>hello 27</p>
        <p>hello 28</p>
        <p>hello 29</p>
        <p>hello 30</p>
        <p>hello 31</p>
        <p>hello 32</p>
        <p>hello 33</p>
        <p>hello 34</p>
        <p>hello 35</p>
        <p>hello 36</p>
        <p>hello 37</p>
        <p>hello 38</p>
        <p>hello 39</p>
        <p>hello 40</p>
        <p>hello 41</p>
        <p>hello 42</p>
        <p>hello 43</p>
        <p>hello 44</p>
        <p>hello 45</p>
        <p>hello 46</p>
        <p>hello 47</p>
        <p>hello 48</p>
        <p>hello 49</p>
        <p>hello 50</p>
        <p>hello 51</p>
        <p>hello 52</p>
        <p>hello 53</p>
        <p>hello 54</p>
        <p>hello 55</p>
        <p>hello 56</p>
        <p>hello 57</p>
        <p>hello 58</p>
        <p>hello 59</p>
        <p>hello 60</p>
        <p>hello 61</p>
        <p>hello 62</p>
        <p>hello 63</p>
        <p>hello 64</p>
        <p>hello 65</p>
        <p>hello 66</p>
        <p>hello 67</p>
        <p>hello 68</p>
        <p>hello 69</p>
        <p>hello 70</p>
        <p>hello 71</p>
        <p>hello 72</p>
        <p>hello 73</p>
        <p>hello 74</p>
        <p>hello 75</p>
        <p>hello 76</p>
        <p>hello 77</p>
        <p>hello 78</p>
        <p>hello 79</p>
        <p>hello 80</p>
        <p>hello 81</p>
        <p>hello 82</p>
        <p>hello 83</p>
        <p>hello 84</p>
        <p>hello 85</p>
        <p>hello 86</p>
        <p>hello 87</p>
        <p>hello 88</p>
        <p>hello 89</p>
        <p>hello 90</p>
        <p>hello 91</p>
        <p>hello 92</p>
        <p>hello 93</p>
        <p>hello 94</p>
        <p>hello 95</p>
        <p>hello 96</p>
        <p>hello 97</p>
        <p>hello 98</p>
        <p>hello 99</p>
        <p>hello 100</p>
        <p>hello 101</p>
        <p>hello 102</p>
        <p>hello 103</p>
        <p>hello 104</p>
        <p>hello 105</p>
        <p>hello 106</p>
        <p>hello 107</p>
        <p>hello 108</p>
        <p>hello 109</p>
        <p>hello 110</p>
        <p>hello 111</p>
        <p>hello 112</p>
        <p>hello 113</p>
        <p>hello 114</p>
        <p>hello 115</p>
        <p>hello 116</p>
        <p>hello 117</p>
        <p>hello 118</p>
        <p>hello 119</p>
        <p>hello 120</p>
        <p>hello 121</p>
        <p>hello 122</p>
        <p>hello 123</p>
        <p>hello 124</p>
        <p>hello 125</p>
        <p>hello 126</p>
        <p>hello 127</p>
        <p>hello 128</p>
        <p>hello 129</p>
        <p>hello 130</p>
        <p>hello 131</p>
        <p>hello 132</p>
        <p>hello 133</p>
        <p>hello 134</p>
        <p>hello 135</p>
        <p>hello 136</p>
        <p>hello 137</p>
        <p>hello 138</p>
        <p>hello 139</p>
        <p>hello 140</p>
        <p>hello 141</p>
        <p>hello 142</p>
        <p>hello 143</p>
        <p>hello 144</p>
        <p>hello 145</p>
        <p>hello 146</p>
        <p>hello 147</p>
        <p>hello 148</p>
        <p>hello 149</p>
        <p>hello 150</p>
        <p>hello 151</p>
        <p>hello 152</p>
        <p>hello 153</p>
        <p>hello 154</p>
        <p>hello 155</p>
        <p>hello 156</p>
        <p>hello 157</p>
        <p>hello 158</p>
        <p>hello 159</p>
        <p>hello 160</p>
        <p>hello 161</p>
        <p>hello 162</p>
        <p>hello 163</p>
        <p>hello 164</p>
        <p>hello 165</p>
        <p>hello 166</p>
        <p>hello 167</p>
        <p>hello 168</p>
        <p>hello 169</p>
        <p>hello 170</p>
        <p>hello 171</p>
        <p>hello 172</p>
        <p>hello 173</p>
        <p>hello 174</p>
        <p>hello 175</p>
        <p>hello 176</p>
        <p>hello 177</p>
        <p>hello 178</p>
        <p>hello 179</p>
        <p>hello 180</p>
        <p>hello 181</p>
        <p>hello 182</p>
        <p>hello 183</p>
        <p>hello 184</p>
        <p>hello 185</p>
        <p>hello 186</p>
        <p>hello 187</p>
        <p>hello 188</p>
        <p>hello 189</p>
        <p>hello 190</p>
        <p>hello 191</p>
        <p>hello 192</p>
        <p>hello 193</p>
        <p>hello 194</p>
        <p>hello 195</p>
        <p>hello 196</p>
        <p>hello 197</p>
        <p>hello 198</p>
        <p>hello 199</p>
        <p>hello 200</p>
      </div>
    </div>
  );
};

export default PrePage;
